# Generated by Django 3.1.7 on 2021-03-26 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetstracking', '0003_auto_20210326_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assetstracking.employee'),
        ),
        migrations.AddField(
            model_name='borrowing',
            name='tag_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assetstracking.tag'),
        ),
    ]
