# Generated by Django 3.1.7 on 2021-03-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetstracking', '0004_auto_20210326_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='subscriber_id',
            field=models.ManyToManyField(to='assetstracking.Subscriber'),
        ),
        migrations.AddField(
            model_name='employee',
            name='subscriber_id',
            field=models.ManyToManyField(to='assetstracking.Subscriber'),
        ),
        migrations.AddField(
            model_name='rfid',
            name='subscriber_id',
            field=models.ManyToManyField(to='assetstracking.Subscriber'),
        ),
        migrations.AddField(
            model_name='tag',
            name='subscriber_id',
            field=models.ManyToManyField(to='assetstracking.Subscriber'),
        ),
    ]
