# Generated by Django 3.1.7 on 2021-04-09 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assetstracking', '0005_auto_20210326_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='asset_id_scanned',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='borrowing',
            name='employee_id_scanned',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='asset_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Taken', 'Taken')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='rfid_id',
            field=models.ManyToManyField(to='assetstracking.RFID'),
        ),
    ]
