# Generated by Django 3.1.7 on 2021-04-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetstracking', '0006_auto_20210410_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_username', models.CharField(max_length=20, null=True)),
                ('client_password', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_salary',
        ),
        migrations.AddField(
            model_name='borrowing',
            name='reader_code',
            field=models.CharField(default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
