# Generated by Django 3.1.7 on 2021-04-22 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetstracking', '0008_tag_asset_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowing',
            name='borrowing_id',
        ),
    ]
