# Generated by Django 3.1.7 on 2021-04-22 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetstracking', '0009_remove_borrowing_borrowing_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowing',
            name='subscriber_id',
        ),
        migrations.AddField(
            model_name='borrowing',
            name='subscriber_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assetstracking.subscriber'),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='subscriber_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='subscriber_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assetstracking.subscriber'),
        ),
        migrations.RemoveField(
            model_name='rfid',
            name='subscriber_id',
        ),
        migrations.AddField(
            model_name='rfid',
            name='subscriber_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assetstracking.subscriber'),
        ),
        migrations.RemoveField(
            model_name='tag',
            name='subscriber_id',
        ),
        migrations.AddField(
            model_name='tag',
            name='subscriber_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assetstracking.subscriber'),
        ),
    ]
